AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LPLivings Store API Backend

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
  GoogleSheetsId:
    Type: String
    Description: Google Sheets ID for data storage
  GoogleCredentials:
    Type: String
    Description: Google Service Account Credentials (JSON)
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        GOOGLE_CLIENT_ID: !Ref GoogleClientId
        GOOGLE_SHEETS_ID: !Ref GoogleSheetsId
        GOOGLE_CREDENTIALS: !Ref GoogleCredentials
        S3_BUCKET: !Ref ProductImagesBucket
    Tags:
      Project: LPLivings-Store
      Environment: !Ref Environment

Resources:
  # S3 Bucket for product images
  ProductImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'lplivings-product-images-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
      Tags:
        - Key: Project
          Value: LPLivings-Store
        - Key: Environment
          Value: !Ref Environment

  # API Gateway
  ECommerceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE

  # Lambda Functions
  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/
      Handler: products.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ProductImagesBucket
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /products
            Method: GET
        PostProduct:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /products
            Method: POST
        OptionsProducts:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /products
            Method: OPTIONS

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/
      Handler: auth.lambda_handler
      Events:
        PostAuth:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /auth
            Method: POST
        OptionsAuth:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /auth
            Method: OPTIONS

  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/
      Handler: orders.lambda_handler
      Events:
        GetOrders:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /orders
            Method: GET
        PostOrder:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /orders
            Method: POST
        OptionsOrders:
          Type: Api
          Properties:
            RestApiId: !Ref ECommerceApi
            Path: /orders
            Method: OPTIONS

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ECommerceApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  S3BucketName:
    Description: S3 bucket for product images
    Value: !Ref ProductImagesBucket